sonar.projectKey=Student-Management-System
sonar.projectName=Student Management System

sonar.sources=admin,student,config,python,index.php

sonar.sourceEncoding=UTF-8

sonar.python.version=3

sonar.exclusions=**/vendor/**,**/__pycache__/**,k8s/**,argocd/**
